"use client";
import { useEffect, useMemo, useState } from "react";
import { TutorialExperience } from "./tutorials/TutorialExperience";
import { IonExchangeTutorial } from "./tutorials/IonExchangeTutorial";
import { MentorPanel } from "./mentor/MentorPanel";
import { evaluateOperation } from "./mentor/mentorEngine.mjs";
import { methods, proteins } from "./data";
import { activity, fractionate, makeInitial, pool, purity, Sample, targetMass, totalProtein, Fraction } from "./science";
type Step={name:string;sample:Sample;cost:number;time:number};
const money=(n:number)=>`$${n.toFixed(0)}`, round=(n:number,d=1)=>n.toFixed(d);

export function Explorer(){
 const [entry,setEntry]=useState<"home"|"tutorial1"|"tutorial2"|"free">("home");
 const [activePortal,setActivePortal]=useState<"tutorial1"|"tutorial2"|"free"|null>(null);
 const navigate=(portal:"tutorial1"|"tutorial2"|"free")=>{setActivePortal(portal);setEntry(portal)};
 useEffect(()=>{if(entry==="tutorial1"||entry==="tutorial2")requestAnimationFrame(()=>document.querySelector<HTMLHeadingElement>(`div:not([hidden]) .tutorial-guide h1`)?.focus())},[entry]);
 return <><div hidden={entry!=="home"}><Welcome active={activePortal} onTutorial1={()=>navigate("tutorial1")} onTutorial2={()=>navigate("tutorial2")} onFree={()=>navigate("free")}/></div><div hidden={entry!=="tutorial1"}><TutorialExperience onExit={()=>navigate("free")} onHome={()=>setEntry("home")}/></div><div hidden={entry!=="tutorial2"}><IonExchangeTutorial onExit={()=>navigate("free")} onHome={()=>setEntry("home")}/></div><div hidden={entry!=="free"}><FreeExplorer onTutorial1={()=>navigate("tutorial1")} onTutorial2={()=>navigate("tutorial2")}/></div></>;
}

function Welcome({active,onTutorial1,onTutorial2,onFree}:{active:"tutorial1"|"tutorial2"|"free"|null;onTutorial1:()=>void;onTutorial2:()=>void;onFree:()=>void}){const card=(id:"tutorial1"|"tutorial2"|"free")=>({className:`entry ${active===id?"selected":""}`,"aria-current":active===id?"page":undefined as "page"|undefined});return <main className="welcome"><section className="welcome-card"><div className="mark large">P</div><span className="eyebrow">PROTEIN PURIFICATION STRATEGY EXPLORER</span><h1>Learn to follow the evidence through a purification.</h1><p>Choose a guided investigation or open the complete explorer and design your own workflow.</p><div className="entry-grid three"><button {...card("tutorial1")} onClick={onTutorial1}><span>GUIDED TUTORIAL 1 · 15–20 MIN</span><b>Find Enzyme A</b><small>Use SEC, activity evidence, and pooling tradeoffs to locate the target.</small><em>{active==="tutorial1"?<><i aria-hidden="true">✓</i> Selected</>:"Start Tutorial 1 →"}</em>{active==="tutorial1"&&<span className="sr-only">Active portal</span>}</button><button {...card("tutorial2")} onClick={onTutorial2}><span>GUIDED TUTORIAL 2 · 15–20 MIN</span><b>Will the Protein Bind?</b><small>Connect pI, pH, resin charge, binding, and salt-gradient elution.</small><em>{active==="tutorial2"?<><i aria-hidden="true">✓</i> Selected</>:"Start Tutorial 2 →"}</em>{active==="tutorial2"&&<span className="sr-only">Active portal</span>}</button><button {...card("free")} onClick={onFree}><span>OPEN WORKSPACE</span><b>Explore Freely</b><small>Choose methods, configure conditions, and build your own purification strategy.</small><em>{active==="free"?<><i aria-hidden="true">✓</i> Selected</>:"Open explorer →"}</em>{active==="free"&&<span className="sr-only">Active portal</span>}</button></div></section></main>}

function FreeExplorer({onTutorial1,onTutorial2}:{onTutorial1:()=>void;onTutorial2:()=>void}){
 const [mode,setMode]=useState("Guided Explorer"), [sample,setSample]=useState<Sample>(makeInitial), [method,setMethod]=useState("salt"), [tab,setTab]=useState("Current Sample"), [bottom,setBottom]=useState("History"), [stage,setStage]=useState(2);
 const [config,setConfig]=useState<any>({low:35,high:62,pH:7.5,exchanger:"anion",gradient:500,fraction:3,load:8});
 const [prediction,setPrediction]=useState({property:"Solubility",target:"Enter the 35–62% pellet",tradeoff:"Purity may rise while recovery falls"});
 const [committed,setCommitted]=useState(false),[fractions,setFractions]=useState<Fraction[]>([]),[selected,setSelected]=useState<string[]>([]),[steps,setSteps]=useState<Step[]>([{name:"Crude lysate",sample:makeInitial(),cost:0,time:0}]),[notes,setNotes]=useState<string[]>([]),[note,setNote]=useState("");
 const [notice,setNotice]=useState("Scenario ready. Inspect the sample, then choose a method."), [showHelp,setShowHelp]=useState(false),[nextAction,setNextAction]=useState(false);
 const [guidance,setGuidance]=useState<"Full"|"Light"|"Off">("Full"),[mentorGoal,setMentorGoal]=useState(""),[mentorEvents,setMentorEvents]=useState<any[]>([]);
 const initial=steps[0].sample, tp=totalProtein(sample), act=activity(sample), p=purity(sample), yieldPct=100*sample.activeTarget/initial.activeTarget, spec=act/tp, fold=spec/(activity(initial)/totalProtein(initial));
 const cost=steps.reduce((a,s)=>a+s.cost,0), time=steps.reduce((a,s)=>a+s.time,0);
 const selectedFs=fractions.filter(f=>selected.includes(f.id));
 const mentorEvaluation=useMemo(()=>evaluateOperation({experimentId:steps.length>1?sample.id:"starting",before:initial,after:sample,operation:steps.length>1?steps[steps.length-1].name:"Starting sample",property:methods.find(m=>m.id===method)?.property||"",costAdded:steps[steps.length-1]?.cost||0,timeAdded:steps[steps.length-1]?.time||0,method,proteins}),[sample,steps,method,initial]);
 const groups=[...new Set(methods.map(m=>m.group))];
 useEffect(()=>{setGuidance(mode==="Purification Challenge"?"Light":"Full")},[mode]);
 function choose(id:string){setMethod(id);const analysis=id==="gel"||id==="assay";setCommitted(analysis);if(id==="gel")setPrediction({property:"Molecular mass",target:"Compare detectable protein complexity in the crude and current samples",tradeoff:"Similarly sized proteins may co-migrate"});else if(id==="assay")setPrediction({property:"Catalytic activity",target:"Determine which sample or fractions contain active Enzyme A",tradeoff:"Inactive target mass does not contribute activity"});setFractions([]);setSelected([]);setNextAction(false);setStage(analysis?5:2);setNotice(analysis?(id==="gel"?"Analysis question: What do you expect the gel to reveal about current protein complexity?":"Analysis question: Which sample or fractions contain active Enzyme A?"):`${methods.find(m=>m.id===id)?.name} selected. Configure settings and commit a prediction.`)}
 function run(){if(!committed){setNotice("Commit your prediction before running this operation.");return} const m=methods.find(x=>x.id===method)!; if(m.status!=="Functional"){setNotice("This method is in the registry but its scientific model is planned for a later phase.");return} if(method==="gel"||method==="assay"){setTab(method==="gel"?"Gel":"Assays");setStage(6);setNextAction(false);setNotice(method==="gel"?"SDS-PAGE complete. Compare the crude lysate with your enriched sample, then interpret the evidence.":"Activity calculated from active Enzyme A, separately from target mass.");return} const fs=fractionate(sample,method,config);setFractions(fs);setSelected(method==="salt"?[fs[1].id]:[]);setTab(method==="salt"?"Fractions":"Chromatogram");setStage(5);setNotice(`${m.name} complete. Inspect the evidence and select fractions to pool.`)}
 function makePool(){if(!selectedFs.length)return; const sourceMethod=method,next=pool(sample,selectedFs),nextSample=sourceMethod==="salt"?{...next,name:"35–62% pellet (Pool F2)"}:next; const c=sourceMethod==="salt"?18:sourceMethod==="iex"?76:115, t=sourceMethod==="salt"?1.25:sourceMethod==="iex"?2:3; setSample(nextSample);setSteps(s=>[...s,{name:nextSample.name,sample:nextSample,cost:c,time:t}]);setFractions([]);setSelected([]);if(sourceMethod==="salt"){setMethod("gel");setPrediction({property:"Molecular mass",target:"Compare detectable protein complexity in the crude and enriched samples",tradeoff:"Similarly sized proteins may co-migrate"});setCommitted(true);setTab("Gel");setStage(6);setNextAction(true);setNotice("Step complete! You isolated a candidate enriched sample. Next: analyze it using SDS-PAGE. Run Experiment is highlighted.")}else{setTab("Current Sample");setStage(7);setNotice(`Created ${nextSample.name}. Mass balance reflects unpooled material left behind.`)}}
 function restart(){const x=makeInitial();setSample(x);setSteps([{name:"Crude lysate",sample:x,cost:0,time:0}]);setFractions([]);setSelected([]);setCommitted(false);setNextAction(false);setStage(1);setNotice("Scenario restarted with seed CHEM214-42.")}
 function undo(){if(steps.length<2)return; const ns=steps.slice(0,-1);setSteps(ns);setSample(ns[ns.length-1].sample);setNotice("Last pooling operation undone; the prior coherent sample state is restored.")}
 function exportBook(){const report={application:"Protein Purification Strategy Explorer",scenario:"Purify Enzyme A from a Bacterial Lysate",seed:"CHEM214-42",mode,studentWork:{prediction,observations:notes},methodSequence:steps.map(s=>s.name),purificationTable:steps.map(row),mentorReasoning:{guidance,selectedGoal:mentorGoal,events:mentorEvents,latestSystemEvaluation:mentorEvaluation},cumulativeCost:cost,cumulativeTimeHours:time};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:"application/json"}));a.download="protein-purification-notebook.json";a.click();URL.revokeObjectURL(a.href)}
 function row(s:Step,i:number){const total=totalProtein(s.sample),a=activity(s.sample),sp=a/total;return {step:i,sample:s.name,volumeMl:s.sample.volume,totalProteinMg:+total.toFixed(2),totalActivity:+a.toFixed(1),specificActivity:+sp.toFixed(2),purityPct:+purity(s.sample).toFixed(1),yieldPct:+(100*s.sample.activeTarget/initial.activeTarget).toFixed(1),purificationFold:+(sp/(activity(initial)/totalProtein(initial))).toFixed(2),cost:s.cost,timeHours:s.time}}
 return <main className={`${nextAction?"next-action":""} ${!nextAction&&["Fractions","Chromatogram","Gel","Assays","Purification Table","Dashboard"].includes(tab)?"evidence-context":""}`}>
  <header className="topbar"><div className="brand"><div className="mark">P</div><div><h1>Protein Purification <span>Strategy Explorer</span></h1><p>Use protein properties to design, test, and evaluate a purification workflow.</p></div></div><div className="header-actions"><button onClick={onTutorial1}>▣ Tutorial 1</button><button onClick={onTutorial2}>▦ Tutorial 2</button><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option>Guided Explorer</option><option>Purification Challenge</option><option disabled>Experimental Design — in development</option></select></label><button onClick={restart}>↻ Restart</button><button onClick={undo} disabled={steps.length<2}>↶ Undo</button><button onClick={exportBook}>⇩ Export</button><button onClick={()=>setShowHelp(true)}>? Help</button></div></header>
  <nav className="stepper investigation-stepper" aria-label="Scientific investigation progress">{["What is in the mixture?","Which property?","What do I predict?","Run separation","What should I keep?","What does evidence show?","Was this a good step?"].map((x,i)=><button key={x} className={stage===i+1?"active":stage>i+1?"done":""} aria-current={stage===i+1?"step":undefined} onClick={()=>setStage(i+1)}><b>{stage>i+1?"✓":stage===i+1?"→":i+1}</b>{x}</button>)}</nav>
  <section className="workspace">
   <aside className="methods"><div className="side-title"><div><span>METHOD LIBRARY</span><h2>Choose a method</h2></div><span className="count">{methods.length}</span></div>{groups.map(g=><section key={g}><h3>{g}</h3>{methods.filter(m=>m.group===g).map(m=><button key={m.id} onClick={()=>choose(m.id)} className={method===m.id?"method active":"method"}><span className="method-icon">{m.group==="Analysis"?"◉":m.group==="Chromatography"?"⇥":"⌁"}</span><span><b>{m.name}</b><small>{m.property} · {m.cost} · {m.time}</small></span><em className={m.status==="Functional"?"ready":"planned"}>{m.status==="Functional"?"READY":"PLANNED"}</em></button>)}</section>)}</aside>
   <section className="center"><div className="scenario"><div><span className="eyebrow">CHEM214 · GUIDED SCENARIO</span><h2>Purify Enzyme A from a Bacterial Lysate</h2><p>Find a defensible path through overlapping protein properties—without losing the enzyme’s activity.</p></div><div className="seed"><span>DETERMINISTIC SEED</span><b>CHEM214-42</b></div></div><MentorPanel evaluation={mentorEvaluation} view={tab} method={method} guidance={guidance} setGuidance={setGuidance} selectedGoal={mentorGoal} onGoal={g=>{setMentorGoal(g.id);setMentorEvents(x=>[...x,{type:"student_goal",goalId:g.id,label:g.label,atStep:steps.length-1}]);setNotice(`${g.label} selected as the next scientific goal. Review the highlighted evidence and tool options; no method has been run.`)}} onView={v=>{setTab(v);setMentorEvents(x=>[...x,{type:"evidence_reviewed",view:v,atStep:steps.length-1}])}}/>
    <nav className="tabs" aria-label="Evidence views">{["Current Sample","Fractions","Chromatogram","Gel","Assays","Purification Table","Dashboard"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
    <div className="canvas">{tab==="Current Sample"&&<SampleView sample={sample} mode={mode} metrics={{tp,act,p,yieldPct,spec,fold}}/>}{tab==="Fractions"&&<Fractions fs={fractions} selected={selected} setSelected={setSelected} pool={makePool}/>} {tab==="Chromatogram"&&<Chromatogram fs={fractions} selected={selected}/>} {tab==="Gel"&&<Gel sample={sample} initial={initial} nextAction={nextAction} onTable={()=>{setTab("Purification Table");setStage(7);setNotice("Evaluate the purification step by integrating protein, activity, yield, fold, and cost.")}}/>} {tab==="Assays"&&<Assays fs={fractions} sample={sample}/>} {tab==="Purification Table"&&<Purification rows={steps.map(row)}/>} {tab==="Dashboard"&&<Dashboard steps={steps} initial={initial}/>}</div>
   </section>
   <aside className="experiment"><div className="panel-head"><span className="eyebrow">EXPERIMENT PANEL</span><span className="ready-dot">● {methods.find(m=>m.id===method)?.status}</span></div><h2>{methods.find(m=>m.id===method)?.name}</h2><div className="property"><span>PROPERTY EXPLOITED</span><b>{methods.find(m=>m.id===method)?.property}</b><p>{methods.find(m=>m.id===method)?.purpose}</p></div><Setup method={method} config={config} setConfig={setConfig}/><div className="warning">△ <span><b>Compatibility check</b>{method==="iex"&&sample.salt>100?" Salt is high for ion-exchange binding. Desalting would improve capture.":method==="sec"&&config.load>10?" Large sample volume will broaden peaks and reduce resolution.":method==="salt"?" Ammonium sulfate remains in retained fractions; plan a future buffer exchange.":" Conditions are acceptable for this educational model."}</span></div><div className="predict"><div><span className="eyebrow">YOUR PREDICTION</span><em>{committed?"COMMITTED":"REQUIRED"}</em></div><label>Property you are exploiting<select value={prediction.property} onChange={e=>setPrediction({...prediction,property:e.target.value})}><option>Solubility</option><option>Net charge</option><option>Molecular size</option><option>Catalytic activity</option></select></label><label>Expected target outcome<textarea value={prediction.target} onChange={e=>setPrediction({...prediction,target:e.target.value})}/></label><button className="commit" onClick={()=>{setCommitted(true);setStage(5);setNotice("Prediction committed. It will remain in the notebook for outcome comparison.")}}>{committed?"✓ Prediction committed":"Commit prediction"}</button></div><div className="estimate"><span><small>EST. COST</small><b>{methods.find(m=>m.id===method)?.cost}</b></span><span><small>EST. TIME</small><b>{methods.find(m=>m.id===method)?.time}</b></span></div><button className="run" onClick={run}>Run experiment <span>→</span></button></aside>
  </section>
  <section className="notebook"><div className="notebook-tabs">{["History","Predictions","Observations","Strategy","Costs","Instructor Feedback"].map(x=><button className={bottom===x?"active":""} onClick={()=>setBottom(x)} key={x}>{x}</button>)}</div><div className="notebook-body"><div><span className="eyebrow">LIVE NOTEBOOK</span><p>{bottom==="History"?`${steps.length} material state${steps.length>1?"s":""} recorded. Current sample: ${sample.name}.`:bottom==="Predictions"?`${committed?"Prediction stored":"No prediction committed yet"}: ${prediction.target}.`:bottom==="Observations"?notes.join(" · ")||"Add an observation linked to the current workflow state.":bottom==="Strategy"?steps.map(s=>s.name).join(" → "):bottom==="Costs"?`${money(cost)} cumulative cost · ${round(time,2)} h cumulative time.`:"Reasonable choices can still yield incomplete separation. Explain the chemistry and tradeoffs."}</p></div>{bottom==="Observations"&&<div className="note-add"><input aria-label="Observation" value={note} onChange={e=>setNote(e.target.value)} placeholder="Record an observation…"/><button onClick={()=>{if(note){setNotes([...notes,note]);setNote("")}}}>Add note</button></div>}<div className="totals"><span><small>CUMULATIVE COST</small><b>{money(cost)}</b></span><span><small>ELAPSED TIME</small><b>{round(time,2)} h</b></span></div></div></section>
  <div className="status" role="status">{notice}</div>
  {showHelp&&<div className="modal" role="dialog" aria-modal="true"><div><button className="close" onClick={()=>setShowHelp(false)}>×</button><span className="eyebrow">GETTING STARTED</span><h2>Build evidence, not a “correct” sequence.</h2><p>Inspect the current mixture, choose a protein property to exploit, configure the method, and commit a prediction. After running, compare the protein signal with enzyme activity before pooling fractions.</p><h3>Key ideas</h3><ul><li>Purity can increase while recovery decreases.</li><li>Target protein mass and active target are tracked separately.</li><li>Overlapping properties create partial resolution.</li><li>Warnings explain compatibility, but do not erase questionable choices.</li></ul><button className="run" onClick={()=>setShowHelp(false)}>Return to explorer</button></div></div>}
 </main>
}

function Setup({method,config,setConfig}:any){if(method==="salt")return <div className="setup"><label>Lower saturation cut <b>{config.low}%</b><input type="range" min="20" max="60" value={config.low} onChange={e=>setConfig({...config,low:+e.target.value})}/></label><label>Upper saturation cut <b>{config.high}%</b><input type="range" min="45" max="85" value={config.high} onChange={e=>setConfig({...config,high:+e.target.value})}/></label><label>Retain<select><option>Intermediate pellet</option><option>Final supernatant</option></select></label></div>;if(method==="iex")return <div className="setup grid"><label>Exchanger<select value={config.exchanger} onChange={e=>setConfig({...config,exchanger:e.target.value})}><option value="anion">Anion (Q)</option><option value="cation">Cation (S)</option></select></label><label>Buffer pH<input type="number" step=".1" value={config.pH} onChange={e=>setConfig({...config,pH:+e.target.value})}/></label><label>Gradient end<input type="number" value={config.gradient} onChange={e=>setConfig({...config,gradient:+e.target.value})}/></label><label>Fraction size<input type="number" value={config.fraction} onChange={e=>setConfig({...config,fraction:+e.target.value})}/></label><div className="ph-scale"><span>pH 4</span><i style={{left:`${(config.pH-4)/6*100}%`}}/><span>pH 10</span></div></div>;if(method==="sec")return <div className="setup"><label>Column<select><option>SEC-75 · 3–80 kDa</option><option>SEC-200 · 10–600 kDa</option></select></label><label>Sample load <b>{config.load} mL</b><input type="range" min="2" max="20" value={config.load} onChange={e=>setConfig({...config,load:+e.target.value})}/></label><label>Fraction size<input type="number" value={config.fraction} onChange={e=>setConfig({...config,fraction:+e.target.value})}/></label></div>;return <div className="setup placeholder"><p>{methods.find(m=>m.id===method)?.status==="Functional"?"This analysis uses the current sample state; no additional configuration is required.":"The setup schema is registered, but this scientific model is intentionally not implemented in Phase 1."}</p></div>}
function SampleView({sample,mode,metrics}:any){return <><div className="sample-head"><div><span className="sample-badge">◈ CURRENT MATERIAL</span><h2>{sample.name}</h2><p>{sample.type} · {sample.volume.toFixed(1)} mL · {sample.buffer}, pH {sample.pH}</p></div><div className="activity-pill">● Enzyme activity retained</div></div><div className="metrics">{[["TOTAL PROTEIN",`${round(metrics.tp)} mg`,"All components"],["TOTAL ACTIVITY",`${round(metrics.act,0)} U`,"Active target only"],["EST. PURITY",`${round(metrics.p)}%`,`${round(metrics.fold,2)}× purification`],["TARGET RECOVERY",`${round(metrics.yieldPct)}%`,`${round(targetMass(sample))} mg target`]].map((x,i)=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small><i className={`metric-icon m${i}`}>{["Σ","✦","◔","↗"][i]}</i></div>)}</div><div className="composition"><div className="section-heading"><div><span className="eyebrow">SAMPLE COMPOSITION</span><h3>Eight detectable proteins</h3></div><div className="legend"><span><i className="target-dot"/> Target</span><span><i/> Contaminants</span></div></div><div className="bars">{proteins.map(p=>{const mass=sample.masses[p.id]||0;return <div key={p.id} className="bar-row"><span>{mode==="Purification Challenge"&&!p.id.includes("enzyme")?`Protein ${p.id[0].toUpperCase()}`:p.name}{p.id==="enzyme-a"&&<em>TARGET</em>}</span><div><i style={{width:`${mass/Math.max(...Object.values(sample.masses))*100}%`,background:p.color}}/></div><b>{round(mass)} mg</b></div>})}</div><div className="property-strip"><span><small>TARGET MASS</small><b>62 kDa</b></span><span><small>TARGET pI</small><b>5.4</b></span><span><small>ACTIVE TARGET</small><b>{round(sample.activeTarget)} mg</b></span><span><small>SALT</small><b>{sample.salt} mM</b></span></div></div></>}
function Fractions({fs,selected,setSelected,pool}:any){if(!fs.length)return <Empty title="No fraction set yet" text="Run ammonium sulfate fractionation or chromatography to generate first-class fractions."/>;return <><div className="section-heading"><div><span className="eyebrow">FRACTION SET</span><h2>Select evidence-informed fractions</h2></div><button className="pool-btn" disabled={!selected.length} onClick={pool}>Pool selected ({selected.length})</button></div><div className="fraction-grid">{fs.map((f:Fraction)=><button className={selected.includes(f.id)?"fraction selected":"fraction"} key={f.id} onClick={()=>setSelected((s:string[])=>s.includes(f.id)?s.filter(x=>x!==f.id):[...s,f.id])}><span>F{f.n}</span><b>{round(totalProtein(f))} mg</b><small>{round(f.activity,0)} U activity</small><i style={{height:`${Math.min(100,f.absorbance*6)}%`}}/></button>)}</div></>}
function Chromatogram({fs,selected}:any){if(!fs.length)return <Empty title="No chromatogram yet" text="Run ion exchange or size exclusion to generate a modeled protein trace."/>;const max=Math.max(...fs.map((f:Fraction)=>f.absorbance));return <><div className="section-heading"><div><span className="eyebrow">MODELED EVIDENCE</span><h2>Protein signal & enzyme activity</h2></div><div className="legend"><span><i/> A₂₈₀</span><span><i className="activity-dot"/> Activity</span></div></div><div className="chart" aria-label="Chromatogram"><div className="y-label">Signal</div><div className="plot">{fs.map((f:Fraction)=><div key={f.id} className={selected.includes(f.id)?"point selected":"point"}><i className="protein" style={{height:`${f.absorbance/max*88}%`}}/><i className="act" style={{height:`${f.activity/Math.max(...fs.map((x:Fraction)=>x.activity))*75}%`}}/><small>{f.n}</small></div>)}</div><div className="x-label">Fraction number →</div></div><table className="accessible-table"><thead><tr><th>Fraction</th><th>Protein signal</th><th>Activity</th></tr></thead><tbody>{fs.map((f:Fraction)=><tr key={f.id}><td>F{f.n}</td><td>{round(f.absorbance,2)}</td><td>{round(f.activity,0)} U</td></tr>)}</tbody></table></>}
function Gel({sample,initial,nextAction,onTable}:{sample:Sample;initial:Sample;nextAction:boolean;onTable:()=>void}){const [answer,setAnswer]=useState("");return <>{nextAction&&<div className="step-transition" role="status"><b>✓ Step complete!</b><span>You isolated a candidate enriched sample.</span><strong>Next: Analyze it using SDS-PAGE.</strong><small>Run Experiment is highlighted in the experiment panel.</small></div>}<div className="section-heading"><div><span className="eyebrow">1D SDS-PAGE · COOMASSIE</span><h2>What changed after fractionation?</h2></div><span className="sample-badge">BEFORE + AFTER</span></div><div className="gel-comparison-free"><div className="gel multi-lane"><div className="markers">{[100,75,50,37,25,15].map(x=><span key={x} style={{top:`${(110-x)/1.15}%`}}>{x}—</span>)}</div><div className="marker-lane"><b>M</b>{[100,75,50,37,25,15].map(x=><i key={x} style={{top:`${(100-x)/1.05}%`}}/>)}</div><GelLane sample={initial} label="1"/><GelLane sample={sample} label="2"/></div><table className="lane-key"><thead><tr><th>Lane</th><th>Sample</th></tr></thead><tbody><tr><td>M</td><td>Molecular-weight marker</td></tr><tr><td>1</td><td>Crude lysate</td></tr><tr><td>2</td><td>{sample.name}</td></tr></tbody></table></div><div className="gel-question"><h3>Does the darkest band identify Enzyme A?</h3><button className={answer==="yes"?"selected incorrect":""} onClick={()=>setAnswer("yes")}>Yes</button><button className={answer==="no"?"selected correct":""} onClick={()=>setAnswer("no")}>No</button>{answer&&<p role="status">{answer==="no"?<><b>Correct.</b> SDS-PAGE shows protein abundance, not enzyme identity. We know where Enzyme A is because of the activity assay.</>:"Not quite. A dark band is abundant protein, but several proteins can share a similar molecular mass. Use the activity assay to identify active Enzyme A."}</p>}</div><div className="gel-interpretation"><span className="eyebrow">INTERPRETATION</span><h3>Mass alone cannot establish identity</h3><p>The crude lysate contains several proteins with molecular masses close to Enzyme A (62 kDa). Chaperonin C (60 kDa) and Regulator X (58 kDa) co-migrate in this region, making the bands difficult to distinguish. Fractionation changes band intensity, but SDS-PAGE separates only by molecular mass. Activity evidence or another purification property is needed to identify the target enzyme.</p></div>{answer==="no"&&<div className="synthesis-next"><b>What should you do next?</b><p>Bring the activity assay, fraction selection, gel, and mass balance together.</p><button onClick={onTable}>Evaluate this step in the Purification Table →</button></div>}</>}
function GelLane({sample,label}:{sample:Sample;label:string}){const max=Math.max(...Object.values(sample.masses));return <div className="lane comparison-lane"><b>{label}</b>{proteins.map(p=><i key={p.id} title={`${p.name}, ${p.mass} kDa`} style={{top:`${(100-p.mass)/1.05}%`,opacity:.12+.8*(sample.masses[p.id]||0)/max,height:Math.max(3,(sample.masses[p.id]||0)/35)}}/>)}</div>}
function Assays({fs,sample}:any){return <><div className="section-heading"><div><span className="eyebrow">ENZYME ACTIVITY ASSAY</span><h2>Activity is tracked separately from target mass</h2></div></div><div className="assay-callout"><span>ACTIVE ENZYME A</span><b>{round(sample.activeTarget)} mg</b><p>{round(activity(sample),0)} total units in the current sample</p></div>{fs.length>0&&<div className="assay-bars">{fs.map((f:Fraction)=><div key={f.id}><span>F{f.n}</span><i style={{width:`${f.activity/Math.max(...fs.map((x:Fraction)=>x.activity))*100}%`}}/><b>{round(f.activity,0)} U</b></div>)}</div>}</>}
function Purification({rows}:any){return <><div className="section-heading"><div><span className="eyebrow">LIVING MASS BALANCE</span><h2>Purification table</h2></div></div><div className="table-scroll"><table><thead><tr>{["Step","Sample","Volume","Total protein","Total activity","Specific activity","Purity","Yield","Fold","Cost","Time"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.step}><td>{r.step}</td><td>{r.sample}</td><td>{r.volumeMl} mL</td><td>{r.totalProteinMg} mg</td><td>{r.totalActivity} U</td><td>{r.specificActivity}</td><td>{r.purityPct}%</td><td>{r.yieldPct}%</td><td>{r.purificationFold}×</td><td>${r.cost}</td><td>{r.timeHours} h</td></tr>)}</tbody></table></div></>}
function Dashboard({steps,initial}:any){return <><div className="section-heading"><div><span className="eyebrow">COMPETING OUTCOMES</span><h2>Strategy trajectory</h2></div></div><div className="dashboard-grid">{[["Purity",(s:Step)=>purity(s.sample),"%"],["Target recovery",(s:Step)=>100*s.sample.activeTarget/initial.activeTarget,"%"],["Active target",(s:Step)=>s.sample.activeTarget," mg"]].map(([name,fn,unit]:any)=><div key={name}><span>{name}</span>{steps.map((s:Step,i:number)=><p key={i}><small>{s.name}</small><i><b style={{width:`${Math.min(100,fn(s))}%`}}/></i><em>{round(fn(s))}{unit}</em></p>)}</div>)}</div></>}
function Empty({title,text}:any){return <div className="empty"><b>⌁</b><h2>{title}</h2><p>{text}</p></div>}
