import { conclusionOptions } from "./guidedJourney.mjs";
import { actionFor } from "./journeyActions.mjs";

export function ScientificJourney({journey,summary,onPrimary,onAlternative,conclusion,onConclusion,onJustification,onSubmitConclusion,conclusionFeedback}:{journey:any;summary:any;onPrimary:()=>void;onAlternative:(id:string)=>void;conclusion:string;onConclusion:(x:string)=>void;onJustification:(x:string)=>void;onSubmitConclusion:()=>void;conclusionFeedback?:string}){
 const current=journey.stages[journey.index],primary=current?actionFor(current.primaryActionId):null;
 if(journey.complete&&journey.investigation.number===1)return <section className="journey-panel complete" aria-label="Scientific Journey"><span className="eyebrow">INVESTIGATION 1 COMPLETE</span><h2>{journey.investigation.title}</h2><EvidenceSummary summary={summary}/><p><b>Student conclusion:</b> Evidence-based response recorded in the Guided Journey record.</p><p><b>System interpretation:</b> Ammonium sulfate fractionation provided {summary.fold>=2?"strong":summary.fold>1?"modest":"limited"} enrichment. The retained sample contains {summary.currentActivity} U activity and {summary.salt} mM modeled salt.</p><div className="journey-primary"><button onClick={()=>onAlternative("begin-charge")}>Begin Investigation 2</button><button className="secondary" onClick={()=>onAlternative("review")}>Review Investigation 1</button><button className="secondary" onClick={()=>onAlternative("free")}>Explore Freely</button></div></section>;
 if(journey.complete)return <section className="journey-panel complete"><span className="eyebrow">SCIENTIFIC JOURNEY COMPLETE</span><h2>{journey.investigation.title}</h2><EvidenceSummary summary={summary}/><p>Two orthogonal properties—solubility and charge—have been evaluated with protein, activity, and recovery evidence.</p></section>;
 return <section className="journey-panel" aria-label="Scientific Journey"><header><div><span className="eyebrow">SCIENTIFIC GUIDE · THINKING LIKE A BIOCHEMIST</span><small>Investigation {journey.investigation.number} of 2</small><h2>{journey.investigation.title}</h2></div><strong>{journey.index+1}/{journey.stages.length}</strong></header><ol className="journey-progress">{journey.stages.map((s:any)=><li key={s.id} className={s.status} aria-current={s.status==="current"?"step":undefined}><b>{s.status==="complete"?"✓":s.status==="current"?"→":"○"}</b>{s.title}</li>)}</ol><div className="journey-current"><span className="eyebrow">CURRENT STEP</span><h3>{current.title}</h3>{journey.index>0&&<div className="just-accomplished"><b>What you just accomplished</b><span>{journey.stages[journey.index-1].completionMessage}</span><b>What you learned</b><span>{journey.stages[journey.index-1].conceptLearned}</span></div>}<p><b>Next recommended activity</b>{current.studentAction}</p><p><b>Why this matters</b>{current.whyItMatters}</p>{current.id.includes("conclusion")?<div className="conclusion-form"><label>{journey.investigation.conclusionPrompt}<select value={conclusion} onChange={e=>onConclusion(e.target.value)}><option value="">Choose a conclusion…</option>{conclusionOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Brief evidence-based justification<textarea onChange={e=>onJustification(e.target.value)} placeholder="Use specific activity, yield, gel, activity, and separation evidence."/></label><button onClick={onSubmitConclusion}>Submit conclusion</button>{conclusionFeedback&&<p role="status">{conclusionFeedback}</p>}</div>:<div className="journey-primary"><button onClick={onPrimary}>{primary?.label||current.primaryActionLabel}</button><details><summary>Other valid options</summary>{current.optionalAlternativeActionIds.map((id:string)=>{const action=actionFor(id);return <button key={id} disabled={!action} title={!action?"This option is unavailable in the current model.":undefined} onClick={()=>action&&onAlternative(id==="review-starting-sample"?"sample":"metrics")}>{action?.label||id}</button>})}</details></div>}{current.id==="evaluate"&&summary.pooled&&<StepComplete summary={summary}/>} {current.id==="gel"&&<div className="coming-next"><b>Coming next in Investigation 2</b><span>Prepare the retained sample and test whether differences in net charge improve separation.</span></div>}</div></section>
}

function EvidenceSummary({summary}:{summary:any}){return <><div className="completion-evidence"><span><b>{summary.proteinDecrease}%</b>Total protein reduction</span><span><b>{summary.specificBefore} → {summary.specificAfter}</b>Specific activity</span><span><b>{summary.fold}×</b>Purification fold</span><span><b>{summary.yieldPct}%</b>Target yield</span><span><b>{summary.initialMajorBands} → {summary.currentMajorBands}</b>Modeled major bands</span><span><b>{summary.currentActivity} U</b>Current activity</span><span><b>{summary.retainedActivityPct}%</b>Activity retained</span><span><b>{summary.salt} mM</b>Current salt</span></div><p><b>Modeled gel evidence:</b> {summary.gelInterpretation}. <b>Modeled activity evidence:</b> {summary.activityInterpretation}.</p></>}

function StepComplete({summary}:{summary:any}){return <section className="step-complete"><span className="eyebrow">STEP COMPLETE</span><h4>Ammonium sulfate fractionation</h4><div><span><b>{summary.proteinDecrease}%</b>less total protein</span><span><b>{summary.yieldPct}%</b>target recovery</span><span><b>{summary.specificBefore} → {summary.specificAfter}</b>U/mg</span></div><p><b>What you learned:</b> Solubility differences removed some contaminants while preserving active Enzyme A.</p><p><b>What remains:</b> Contaminating protein and high salt remain.</p></section>}

export function ChallengeGoals({onGoal}:{onGoal:(id:string)=>void}){const groups:any={"Evaluate the sample":[["gel","Analyze protein complexity",true],["assay","Determine whether Enzyme A remains active",true],["table","Review purification metrics",true],["dashboard","Compare before and after",true]],"Prepare the sample":[["desalt","Remove salt or exchange buffer",true],["ph","Adjust pH",true],["concentrate","Reduce sample volume",false]],"Continue purifying":[["iex","Exploit net charge",true],["sec","Exploit molecular size",true],["affinity","Exploit ligand specificity",false],["hic","Exploit hydrophobicity",false]],"Finish or revise":[["evaluate","Evaluate the strategy",true],["alternative","Compare with an alternative",false],["finish","Finish and export",true]]};return <section className="challenge-goals"><span className="eyebrow">SCIENTIFIC GOALS</span><h2>Choose and defend the next priority</h2><div>{Object.entries(groups).map(([name,items]:any)=><section key={name}><h3>{name}</h3>{items.map(([id,label,enabled]:any)=><button key={id} disabled={!enabled} title={!enabled?"This model is planned and not yet available.":undefined} onClick={()=>enabled&&onGoal(id)}>{label}{!enabled&&<small> · planned</small>}</button>)}</section>)}</div></section>}

export function ChargeOrientation({onPrepare,onFresh}:{onPrepare:()=>void;onFresh:()=>void}){return <section className="charge-orientation"><span className="eyebrow">INVESTIGATION 2 OF 2</span><h2>Can differences in charge improve the purification further?</h2><p>Enzyme A is near 62 kDa, and several remaining proteins have similar molecular masses. They can co-migrate on SDS-PAGE and overlap during size-exclusion chromatography. Net charge provides a different basis for discrimination.</p><ul><li>High ammonium sulfate competes with protein–resin electrostatic interactions and can prevent effective ion-exchange binding.</li><li>Inspect buffer pH and compare it with target and contaminant pI values.</li><li>Predict binding before running chromatography.</li></ul><b>High-salt material is not silently reused and planned dialysis is not represented as student work.</b><div><button onClick={onPrepare}>Review preparation guidance</button><button onClick={onFresh}>Begin with instructor-prepared compatible sample</button></div></section>}
