import { conclusionOptions } from "./guidedJourney.mjs";

export function ScientificJourney({journey,summary,onPrimary,onAlternative,conclusion,onConclusion,onJustification,onSubmitConclusion,conclusionFeedback}:{journey:any;summary:any;onPrimary:()=>void;onAlternative:(id:string)=>void;conclusion:string;onConclusion:(x:string)=>void;onJustification:(x:string)=>void;onSubmitConclusion:()=>void;conclusionFeedback?:string}){
 const current=journey.stages[journey.index];
 if(journey.complete)return <section className="journey-panel complete" aria-label="Scientific Journey"><span className="eyebrow">INVESTIGATION 1 COMPLETE</span><h2>{journey.investigation.title}</h2><div className="completion-evidence"><span><b>{summary.purityBefore}% → {summary.purityAfter}%</b>Purity</span><span><b>{summary.specificBefore} → {summary.specificAfter}</b>Specific activity</span><span><b>{summary.yieldPct}%</b>Target recovery</span></div><p><b>Conclusion:</b> Ammonium sulfate fractionation provided {summary.fold>=2?"strong":summary.fold>1?"modest":"limited"} enrichment while retaining {summary.yieldPct>=70?"acceptable":"reduced"} activity.</p><p><b>Remaining limitation:</b> Substantial contaminating protein and high ammonium sulfate remain.</p><div className="journey-primary"><button onClick={()=>onAlternative("begin-charge")}>Begin Investigation 2</button><button className="secondary" onClick={()=>onAlternative("review")}>Review Investigation 1</button><button className="secondary" onClick={()=>onAlternative("free")}>Explore Freely</button></div></section>;
 return <section className="journey-panel" aria-label="Scientific Journey"><header><div><span className="eyebrow">SCIENTIFIC GUIDE · THINKING LIKE A BIOCHEMIST</span><small>Investigation {journey.investigation.number} of 2</small><h2>{journey.investigation.title}</h2></div><strong>{journey.index+1}/{journey.stages.length}</strong></header><ol className="journey-progress">{journey.stages.map((s:any)=><li key={s.id} className={s.status} aria-current={s.status==="current"?"step":undefined}><b>{s.status==="complete"?"✓":s.status==="current"?"→":"○"}</b>{s.title}</li>)}</ol><div className="journey-current"><span className="eyebrow">CURRENT STEP</span><h3>{current.title}</h3>{journey.index>0&&<div className="just-accomplished"><b>What you just accomplished</b><span>{journey.stages[journey.index-1].completionMessage}</span><b>What you learned</b><span>{journey.stages[journey.index-1].conceptLearned}</span></div>}<p><b>Next recommended activity</b>{current.studentAction}</p><p><b>Why this matters</b>{current.whyItMatters}</p>{current.id==="conclusion"?<div className="conclusion-form"><label>{journey.investigation.conclusionPrompt}<select value={conclusion} onChange={e=>onConclusion(e.target.value)}><option value="">Choose a conclusion…</option>{conclusionOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Brief evidence-based justification<textarea onChange={e=>onJustification(e.target.value)} placeholder="Use specific activity, yield, gel, and activity evidence."/></label><button onClick={onSubmitConclusion}>Submit conclusion</button>{conclusionFeedback&&<p role="status">{conclusionFeedback}</p>}</div>:<div className="journey-primary"><button onClick={onPrimary}>{current.primaryActionLabel}</button><details><summary>Other valid options</summary><button onClick={()=>onAlternative("sample")}>Review Current Sample</button><button onClick={()=>onAlternative("metrics")}>Review purification metrics</button></details></div>}{current.id==="evaluate"&&summary.pooled&&<StepComplete summary={summary}/>} {current.id==="gel"&&<div className="coming-next"><b>Coming next in Investigation 2</b><span>Prepare the retained sample and test whether differences in net charge improve separation.</span></div>}</div></section>
}

function StepComplete({summary}:{summary:any}){return <section className="step-complete"><span className="eyebrow">STEP COMPLETE</span><h4>Ammonium sulfate fractionation</h4><div><span><b>{summary.proteinDecrease}%</b>less total protein</span><span><b>{summary.yieldPct}%</b>target recovery</span><span><b>{summary.specificBefore} → {summary.specificAfter}</b>U/mg</span></div><p><b>What you learned:</b> Solubility differences removed some contaminants while preserving active Enzyme A.</p><p><b>What remains:</b> Contaminating protein and high salt remain.</p></section>}

export function ChallengeGoals({onGoal}:{onGoal:(id:string)=>void}){const groups={"Evaluate the sample":[["gel","Analyze protein complexity"],["assay","Determine whether Enzyme A remains active"],["table","Review purification metrics"],["dashboard","Compare before and after"]],"Prepare the sample":[["desalt","Remove salt or exchange buffer"],["ph","Adjust pH"],["concentrate","Reduce sample volume"]],"Continue purifying":[["iex","Exploit net charge"],["sec","Exploit molecular size"],["affinity","Exploit ligand specificity"],["hic","Exploit hydrophobicity"]],"Finish or revise":[["evaluate","Evaluate the strategy"],["alternative","Compare with an alternative"],["finish","Finish and export"]]};return <section className="challenge-goals"><span className="eyebrow">SCIENTIFIC GOALS</span><h2>Choose and defend the next priority</h2><div>{Object.entries(groups).map(([name,items])=><section key={name}><h3>{name}</h3>{items.map(([id,label])=><button key={id} onClick={()=>onGoal(id)}>{label}</button>)}</section>)}</div></section>}

export function ChargeOrientation({onPrepare,onFresh}:{onPrepare:()=>void;onFresh:()=>void}){return <section className="charge-orientation"><span className="eyebrow">INVESTIGATION 2 OF 2</span><h2>Can differences in charge improve the purification further?</h2><p>The retained sample is enriched but still contains contaminants. Ion-exchange chromatography tests whether differences in net charge can provide better separation.</p><ul><li>Remove or reduce ammonium sulfate.</li><li>Inspect buffer pH and compare it with protein pI.</li><li>Predict binding before running chromatography.</li></ul><b>High-salt material is not silently reused.</b><div><button onClick={onPrepare}>Prepare current sample</button><button onClick={onFresh}>Begin with a prepared compatible sample</button></div></section>}
