import { decisionQuestions, revealLimits, viewIntroductions, viewPurpose } from "./workflowGuide.mjs";

export function CurrentInvestigation({guide,mode,onMode}:{guide:any;mode:string;onMode:(x:string)=>void}){
 return <section className={`current-investigation ${mode.toLowerCase()}`} aria-label="Current Investigation"><div className="investigation-head"><div><span className="eyebrow">CURRENT INVESTIGATION</span><h2>{guide.current}</h2></div><label>Navigation guidance<select value={mode} onChange={e=>onMode(e.target.value)}><option>Full</option><option>Compact</option><option>Off</option></select></label></div>{mode==="Full"&&<div className="investigation-grid"><p><b>Why this matters</b>{guide.why}</p><p><b>What this step reveals</b>{guide.reveals}</p><p><b>Next action</b>{guide.next}</p></div>}{mode==="Compact"&&<p className="compact-next"><b>Next:</b> {guide.next}</p>}</section>
}
export function ViewIntroduction({view,mode}:{view:string;mode:string}){if(mode==="Off")return null;const intro=viewIntroductions[view];return <section className="view-introduction" aria-labelledby="active-view-title"><div><span className="eyebrow">ACTIVE VIEW</span><h2 id="active-view-title" tabIndex={-1}>{view}</h2><p>{viewPurpose[view]}</p></div>{mode==="Full"&&intro&&<div className="view-instruction"><p><b>Look for</b>{intro.look}</p><p><b>Next</b>{intro.next}</p></div>}</section>}
export function RevealPanel({view}:{view:string}){const item=revealLimits[view];if(!item)return null;return <details className="reveal-panel"><summary>What this step reveals</summary><div><section><b>Can reveal</b><ul>{item.can.map(x=><li key={x}>{x}</li>)}</ul></section><section><b>Cannot prove</b><ul>{item.cannot.map(x=><li key={x}>{x}</li>)}</ul></section></div></details>}
export function DecisionQuestion({view}:{view:string}){const q=decisionQuestions[view];return q?<p className="decision-question"><b>Decision question:</b> {q}</p>:null}
export function NextActionCard({title,reason,primaryLabel,onPrimary,alternativeLabel,onAlternative,disabled,disabledReason}:{title:string;reason:string;primaryLabel:string;onPrimary:()=>void;alternativeLabel?:string;onAlternative?:()=>void;disabled?:boolean;disabledReason?:string}){return <section className="next-recommended" aria-label="Next recommended action"><span className="eyebrow">NEXT RECOMMENDED ACTION</span><h3>{title}</h3><p>{reason}</p><div><button disabled={disabled} aria-describedby={disabled&&disabledReason?"next-disabled-reason":undefined} onClick={onPrimary}>{primaryLabel}</button>{alternativeLabel&&onAlternative&&<button className="alternative" onClick={onAlternative}>{alternativeLabel}</button>}</div>{disabled&&disabledReason&&<small id="next-disabled-reason">{disabledReason}</small>}</section>}
