const pct=(before,after)=>before?100*(after-before)/before:0;
export function evaluateOperation({experimentId="current",before,after,operation="Current operation",property="",costAdded=0,timeAdded=0,method="",proteins=[]}){
 const total=s=>Object.values(s.masses).reduce((a,b)=>a+b,0),target=s=>s.masses["enzyme-a"]||0,act=s=>s.activeTarget*82;
 const bp=total(before),ap=total(after),ba=act(before),aa=act(after),bs=ba/bp,as=aa/ap,bpur=100*target(before)/bp,apur=100*target(after)/ap,yieldPct=100*after.activeTarget/before.activeTarget,fold=as/bs;
 const metricChanges={totalProteinPercentChange:pct(bp,ap),totalActivityPercentChange:pct(ba,aa),specificActivityPercentChange:pct(bs,as),purityPercentChange:pct(bpur,apur),yield:yieldPct,purificationFold:fold,costAdded,timeAdded,before:{protein:bp,activity:ba,specific:bs,purity:bpur},after:{protein:ap,activity:aa,specific:as,purity:apur}};
 const outcomes=[];if(apur>bpur*1.05)outcomes.push("purity_improved");if(yieldPct>=65)outcomes.push("yield_acceptable");if(fold<1.15&&yieldPct>=75)outcomes.push("high_yield_low_purification");if(fold>=1.15&&yieldPct<65)outcomes.push("purity_improved_yield_low");if(after.activeTarget/before.activeTarget<target(after)/Math.max(target(before),.001)*.8)outcomes.push("activity_loss_without_target_mass_loss");if(after.name.includes("pellet")||after.salt>100)outcomes.push("salt_high");if(apur<85)outcomes.push("contaminants_remain");
 const unresolvedProblems=[];if(outcomes.includes("salt_high"))unresolvedProblems.push("buffer_incompatible_with_ion_exchange");const t=proteins.find(p=>p.id==="enzyme-a");if(t&&proteins.some(p=>p.id!==t.id&&Math.abs(p.mass-t.mass)<=4))unresolvedProblems.push("target_overlaps_similar_mass_contaminants");if(t&&proteins.some(p=>p.id!==t.id&&Math.abs(p.pI-t.pI)<=.5))unresolvedProblems.push("target_overlaps_similar_charge_contaminants");
 const classification=fold>=1.5&&yieldPct>=65?"strong_enrichment":fold>=1.15&&yieldPct>=65?"modest_enrichment":fold<1.15&&yieldPct>=75?"high_recovery_low_purification":yieldPct<65&&apur>bpur?"cleaner_with_activity_cost":"additional_evidence_needed";
 return {experimentId,operation,property,metricChanges,retainedConditions:{pH:after.pH,saltConcentration:after.salt,volume:after.volume,ammoniumSulfateRetained:after.name.includes("pellet")},evidenceAvailable:{purificationTable:true,gel:true,activityAssay:true},detectedOutcomes:outcomes,unresolvedProblems,classification,method};
}
export function evaluateFractions(fractions,ids){const picked=fractions.filter(f=>ids.includes(f.id)),allAct=fractions.reduce((s,f)=>s+f.activity,0),act=picked.reduce((s,f)=>s+f.activity,0),target=picked.reduce((s,f)=>s+(f.masses["enzyme-a"]||0),0),contaminant=picked.reduce((s,f)=>s+Object.entries(f.masses).filter(([id])=>id!=="enzyme-a").reduce((a,[,v])=>a+v,0),0),recovery=act/Math.max(allAct,.001),purity=target/Math.max(target+contaminant,.001);return {recovery,purity,contaminantBurden:contaminant,classification:!picked.length||recovery<.3?"misses_most_target":picked.length>7?"target_rich_overly_broad":recovery>.65&&purity>.2?"target_rich_balanced":recovery>.75?"high_recovery_low_enrichment":"target_rich_too_narrow"}}
export function goalsFor(e){const goals=[{id:"analyze",label:"Analyze protein complexity",reason:"A before/after gel can reveal how mixture complexity changed.",views:["Gel"],methods:["gel"]},{id:"activity",label:"Determine whether Enzyme A remains active",reason:"Activity evidence distinguishes functional target from total protein.",views:["Assays"],methods:["assay"]},{id:"purify",label:"Exploit a different protein property",reason:"A second property may distinguish contaminants that remain.",views:["Current Sample"],methods:["iex","sec","affinity"]},{id:"evaluate",label:"Review the purification result",reason:"The table integrates enrichment, recovery, cost, and time.",views:["Purification Table"],methods:[]},{id:"finish",label:"Finish and evaluate the strategy",reason:"Decide whether the current evidence supports stopping.",views:["Dashboard"],methods:[]}];if(e.detectedOutcomes.includes("salt_high"))goals.splice(1,0,{id:"desalt",label:"Remove salt or exchange buffer",reason:"High salt may prevent effective ion-exchange binding.",views:["Current Sample"],methods:["dialysis"]});return goals}
export function mentorNarrative(e,view,method){const m=e.metricChanges,changed=e.experimentId!=="starting";return {phase:view==="Purification Table"?"INTERPRET":view==="Gel"||view==="Assays"||view==="Chromatogram"?"ANALYZE":view==="Fractions"?"DECIDE":changed?"CONTINUE_OR_FINISH":"ORIENT",question:view==="Gel"?"What does the band pattern reveal about protein complexity?":view==="Assays"?"Which material contains active Enzyme A?":view==="Purification Table"?"Did this operation improve the sample enough to justify its tradeoffs?":changed?"Which limitation should the next operation address?":"What do you know about the starting mixture?",happened:changed?[`Total protein ${m.totalProteinPercentChange<=0?"decreased":"increased"} by ${Math.abs(m.totalProteinPercentChange).toFixed(1)}%.`,`Target recovery is ${m.yield.toFixed(1)}%.`,`Specific activity changed from ${m.before.specific.toFixed(2)} to ${m.after.specific.toFixed(2)} U/mg.`]:[],interpretation:e.classification==="strong_enrichment"?"Strong enrichment with acceptable recovery.":e.classification==="modest_enrichment"?"Useful but modest enrichment: contaminants were removed while most active target was retained.":e.classification==="high_recovery_low_purification"?"The target was retained, but little contaminating protein was removed.":e.classification==="cleaner_with_activity_cost"?"Purity improved at a substantial cost in target activity.":"Additional evidence is needed before judging this step.",problems:[...(e.detectedOutcomes.includes("contaminants_remain")?["Substantial contaminating protein remains."]:[]),...(e.detectedOutcomes.includes("salt_high")?["The retained sample remains high in salt; low-salt ion-exchange binding may be limited."]:[]),...(method==="iex"&&e.retainedConditions.saltConcentration>100?["At this salt concentration, proteins may not bind effectively to ion-exchange resin."]:[]),...(e.unresolvedProblems.includes("target_overlaps_similar_mass_contaminants")?["Proteins close to 62 kDa may co-migrate or overlap during size-based separation."]:[])]}}
