import {useEffect,useMemo,useRef,useState} from "react";
import type {ReactNode} from "react";
import {bindingPrediction,modeledProteins,proteinCharge,resinCharge} from "./ionExchangeEngine.mjs";
import {downloadCompletionPdf} from "./completionRecord.mjs";

const steps=["Compare pH and pI","Identify Resin Charge","Predict Binding","Explore Parameters","Interpret Salt Gradient","Compare Proteins"];
type Answers=Record<string,string>;type Attempts=Record<string,number>;
export function IonExchangeTutorial({onExit,onHome}:{onExit:()=>void;onHome:()=>void}){
 const [step,setStep]=useState(0),[answers,setAnswers]=useState<Answers>({}),[attempts,setAttempts]=useState<Attempts>({}),[message,setMessage]=useState("Start by comparing buffer pH with protein pI."),[pI,setPI]=useState(8.5),[pH,setPH]=useState(6.5),[resin,setResin]=useState<"cation"|"anion">("cation"),[salt,setSalt]=useState(25),[gradient,setGradient]=useState(500),[revealed,setRevealed]=useState(false),[completed,setCompleted]=useState(false),[studentName,setStudentName]=useState(""),[recordId,setRecordId]=useState("");
 const heading=useRef<HTMLHeadingElement>(null),charge=proteinCharge(pI,pH),binding=bindingPrediction({pI,pH,resinType:resin,startSalt:salt}),comparison=useMemo(()=>modeledProteins(6.5,"cation"),[]);
 useEffect(()=>heading.current?.focus(),[step]);
 const respond=(key:string,value:string,correct:boolean)=>{setAnswers(a=>({...a,[key]:value}));setAttempts(a=>({...a,[key]:(a[key]||0)+1}));setMessage(correct?"Correct. Continue when you are ready.":"Not yet. Use the charge summary and explanatory rule, then try again.")};
 const next=()=>{setStep(s=>Math.min(5,s+1));setMessage(`Step ${Math.min(6,step+2)} ready.`)};
 const done=(key:string,value:string)=>answers[key]===value;
 function pdf(){if(!studentName.trim()){setMessage("Enter your full name before generating the PDF record.");return}const record=downloadCompletionPdf({studentName,tutorialNumber:"Guided Tutorial 2",tutorialTitle:"Will the Protein Bind?",version:"1.0",responses:{...answers,"final parameters":`pI ${pI}, pH ${pH}, ${resin} exchanger, ${salt}-${gradient} mM salt`},attempts,outcome:{"predicted protein charge":charge,"resin charge":resinCharge(resin),"expected result":binding.result,"modeled elution":binding.elution?`${binding.elution.toFixed(0)} mM salt`:"flow-through"}});setRecordId(record.completionId);setMessage("PDF tutorial record downloaded. Submit your own record to Canvas.")}
 return <main className="tutorial-shell">
  <header className="tutorial-top"><button className="brand-button" onClick={onHome}><span className="mark">P</span><span><b>Protein Purification</b><small>Strategy Explorer</small></span></button><div><b>Guided Tutorial 2</b><small>Will the Protein Bind? · 15–20 min</small></div><button onClick={onExit}>Exit to free explorer</button></header>
  <nav className="tutorial-progress" aria-label="Tutorial 2 progress">{steps.map((s,i)=><button key={s} className={i===step?"active":i<step?"done":""} disabled={i>step} onClick={()=>i<=step&&setStep(i)}><span>{i<step?"✓":i+1}</span><small>{s}</small></button>)}</nav>
  <section className="tutorial-layout ion-layout"><aside className="tutorial-guide"><span className="eyebrow">STEP {step+1} OF 6</span><h1 ref={heading} tabIndex={-1}>{steps[step]}</h1><p>{["Predict net charge from the relationship between pH and pI.","Learn what cation and anion exchangers actually capture.","Combine protein charge and resin charge to predict binding.","Test how conditions change modeled binding and elution.","Explain how an increasing salt gradient elutes a bound protein.","Compare three proteins and defend an elution order."][step]}</p><div className="advanced-note"><b>Advanced note</b><p>pI provides a useful first prediction, but actual binding also depends on the distribution and accessibility of charged groups on the protein surface.</p></div></aside>
   <section className="tutorial-stage"><ChargeSummary pI={pI} pH={pH} resin={resin} result={binding.result}/>
    {step===0&&<><Lesson title="Compare pH and pI">If pH is below pI, a protein tends to be net positive. If pH is above pI, it tends to be net negative. Near its pI, it has little net charge and may bind weakly or unpredictably.</Lesson><Question prompt="Protein X has pI 8.5 in buffer at pH 6.5. What is its predicted net charge?" options={["positive","approximately neutral","negative"]} onChoose={x=>respond("charge",x,x==="positive")}/><Feedback ok={done("charge","positive")} attempted={!!answers.charge} message={message}/><Continue enabled={done("charge","positive")} onClick={next}/></>}
    {step===1&&<><Lesson title="Names describe the captured ion"><b>Cation exchanger:</b> a negatively charged resin that binds positively charged proteins.<br/><b>Anion exchanger:</b> a positively charged resin that binds negatively charged proteins.</Lesson><div className="resin-pair"><div><b>Cation exchanger</b><span>Resin charge: −</span><small>Captures positive proteins</small></div><div><b>Anion exchanger</b><span>Resin charge: +</span><small>Captures negative proteins</small></div></div><Question prompt="What is the charge of a cation-exchange resin?" options={["negative","positive"]} onChoose={x=>respond("resin-charge",x,x==="negative")}/><Feedback ok={done("resin-charge","negative")} attempted={!!answers["resin-charge"]} message={message}/><Continue enabled={done("resin-charge","negative")} onClick={next}/></>}
    {step===2&&<><Lesson title="Opposite charges attract">Protein X tends to be positive at pH 6.5. A negatively charged cation exchanger is therefore expected to bind it, all other conditions being equal.</Lesson><Question prompt="Which resin is more likely to bind Protein X, and why?" options={["Cation exchanger—its negative resin attracts positive Protein X","Anion exchanger—its positive resin attracts positive Protein X","Neither—pI never predicts binding"]} onChoose={x=>respond("binding-reason",x,x.startsWith("Cation"))}/><Feedback ok={answers["binding-reason"]?.startsWith("Cation")||false} attempted={!!answers["binding-reason"]} message={message}/><Continue enabled={answers["binding-reason"]?.startsWith("Cation")||false} onClick={next}/></>}
    {step===3&&<><Lesson title="Explore parameter changes">Adjust the model. The summary and modeled elution position update immediately.</Lesson><div className="ion-controls"><label>Protein pI <b>{pI.toFixed(1)}</b><input type="range" min="4" max="10" step=".1" value={pI} onChange={e=>setPI(+e.target.value)}/></label><label>Buffer pH <b>{pH.toFixed(1)}</b><input type="range" min="4" max="10" step=".1" value={pH} onChange={e=>setPH(+e.target.value)}/></label><label>Resin type<select value={resin} onChange={e=>setResin(e.target.value as "cation"|"anion")}><option value="cation">Cation exchanger (negative resin)</option><option value="anion">Anion exchanger (positive resin)</option></select></label><label>Starting salt <b>{salt} mM</b><input type="range" min="0" max="200" step="10" value={salt} onChange={e=>setSalt(+e.target.value)}/></label><label>Gradient end <b>{gradient} mM</b><input type="range" min="200" max="800" step="25" value={gradient} onChange={e=>setGradient(+e.target.value)}/></label></div><IonChromatogram elution={binding.elution} gradient={gradient} label="Protein X"/><button className="tutorial-cta" onClick={()=>{respond("parameter-exploration",`${charge}; ${binding.result}`,true);next()}}>Save observation and continue →</button></>}
    {step===4&&<><Lesson title="Salt competes for electrostatic interactions">As salt concentration increases, salt ions compete with charged proteins for interactions with the resin. More strongly bound proteins generally require a higher salt concentration to elute. Salt does not change the protein's identity.</Lesson><IonChromatogram elution={260} gradient={500} label="Bound Protein X"/><Question prompt="Why does Protein X elute during the increasing salt gradient?" options={["Salt ions compete with the bound protein for electrostatic interactions","Salt changes Protein X into a different protein","A₂₈₀ forces the protein off the resin"]} onChoose={x=>respond("salt-elution",x,x.startsWith("Salt ions compete"))}/><Feedback ok={answers["salt-elution"]?.startsWith("Salt ions compete")||false} attempted={!!answers["salt-elution"]} message={message}/><Continue enabled={answers["salt-elution"]?.startsWith("Salt ions compete")||false} onClick={next}/></>}
    {step===5&&<><Lesson title="Compare three proteins">At pH 6.5 on a cation exchanger, predict which proteins flow through and which bind. Among bound proteins, stronger modeled binding requires more salt to elute.</Lesson><table className="protein-compare"><thead><tr><th>Protein</th><th>pI</th><th>Predicted charge</th></tr></thead><tbody>{comparison.map(p=><tr key={p.name}><td>{p.name}</td><td>{p.pI}</td><td>{revealed?p.charge:"Predict first"}</td></tr>)}</tbody></table>{!revealed?<><Question prompt="Which pattern is most defensible?" options={["X binds most strongly; Y may bind weakly; Z flows through","Z binds most strongly; X flows through","All proteins bind equally"]} onChoose={x=>{respond("protein-order",x,x.startsWith("X binds"));if(x.startsWith("X binds"))setRevealed(true)}}/><Feedback ok={answers["protein-order"]?.startsWith("X binds")||false} attempted={!!answers["protein-order"]} message={message}/></>:<><MultiChromatogram proteins={comparison}/><div className="science-note success"><b>Modeled result</b><p>Protein Z is negative and flows through. Protein Y is near its pI and may bind weakly. Protein X is positive and is expected to bind most strongly, eluting later as salt rises.</p></div>{!completed?<button className="tutorial-cta" onClick={()=>{setCompleted(true);setMessage("Tutorial 2 complete. Enter your name to create a Canvas-ready PDF record.")}}>Complete Tutorial 2 →</button>:<div className="completion"><span>✓</span><h2>Tutorial 2 complete</h2><p>You connected pI, pH, protein charge, resin charge, binding, and salt-gradient elution.</p><label className="student-name">Full name<input value={studentName} onChange={e=>setStudentName(e.target.value)} autoComplete="off" placeholder="Enter your full name"/></label><button disabled={!studentName.trim()} onClick={pdf}>Download PDF Tutorial Record</button><p className="privacy-note">Your record includes your name, completion time, responses, and a unique completion ID. Submit your own record to Canvas. Your name stays in this session and is not transmitted or permanently stored.</p>{recordId&&<small>Completion ID: {recordId}</small>}</div>}</>}</>}
   </section></section><div className="tutorial-status" aria-live="polite">{message}</div>
 </main>
}
function ChargeSummary({pI,pH,resin,result}:{pI:number;pH:number;resin:"cation"|"anion";result:string}){return <aside className="charge-summary" aria-label="Current charge reasoning"><div><b>Protein</b><span>pI: {pI.toFixed(1)}</span><span>Buffer pH: {pH.toFixed(1)}</span><span>Predicted charge: {proteinCharge(pI,pH)}</span></div><div><b>Resin</b><span>Type: {resin} exchanger</span><span>Resin charge: {resinCharge(resin)}</span><span>Expected result: {result}</span></div></aside>}
function Lesson({title,children}:{title:string;children:ReactNode}){return <div className="tutorial-title"><span className="eyebrow">ION-EXCHANGE REASONING</span><h2>{title}</h2><p>{children}</p></div>}
function Question({prompt,options,onChoose}:{prompt:string;options:string[];onChoose:(x:string)=>void}){return <div className="knowledge"><p>{prompt}</p>{options.map(x=><button key={x} onClick={()=>onChoose(x)}>{x}</button>)}</div>}
function Feedback({ok,attempted,message}:{ok:boolean;attempted:boolean;message:string}){return <div className={attempted?(ok?"feedback correct":"feedback retry"):"feedback"} role="status">{attempted&&message}</div>}
function Continue({enabled,onClick}:{enabled:boolean;onClick:()=>void}){return <button className="tutorial-cta" disabled={!enabled} onClick={onClick}>Continue →</button>}
function IonChromatogram({elution,gradient,label}:{elution:number;gradient:number;label:string}){const pos=elution?Math.min(94,Math.max(8,elution/gradient*100)):5;return <div className="ion-chart" aria-label={`Modeled ion-exchange chromatogram for ${label}`}><div className="flow-peak" style={{left:elution?"2%":`${pos}%`}}/><div className="bound-peak" style={{left:`${pos}%`,display:elution?"block":"none"}}/><i/><span>Flow-through</span><b style={{left:`${pos}%`}}>{elution?`${label}: ~${elution.toFixed(0)} mM`:label}</b><small>Increasing salt concentration → {gradient} mM</small></div>}
function MultiChromatogram({proteins}:{proteins:any[]}){return <div className="multi-ion-chart" aria-label="Revealed modeled chromatogram">{proteins.map((p,i)=><div key={p.name} style={{left:p.elution?`${Math.min(92,p.elution/5)}%`:`${5+i*3}%`}}><i/><b>{p.name}</b><small>{p.elution?`${p.elution.toFixed(0)} mM`:"flow-through"}</small></div>)}</div>}
