import {useEffect,useMemo,useRef,useState} from "react";
import {proteins} from "../data";
import {activity,fractionate,makeInitial,pool,purity,totalProtein,type Fraction,type Sample} from "../science";
import {tutorialOne} from "./tutorialRegistry";
import {closestContaminant,initialTutorialState,selectionEvaluation,supportedInterpretations,type TutorialState} from "./tutorialEngine.mjs";
import {downloadCompletionPdf} from "./completionRecord.mjs";
import {evaluateOperation} from "../mentor/mentorEngine.mjs";

const round=(n:number,d=1)=>n.toFixed(d);
const answerClass=(answered:boolean,correct:boolean)=>answered?(correct?"feedback correct":"feedback retry"):"feedback";

export function TutorialExperience({onExit,onHome}:{onExit:()=>void;onHome:()=>void}){
 const initial=useMemo(makeInitial,[]), [state,setState]=useState<TutorialState>(initialTutorialState), [sample,setSample]=useState<Sample>(initial), [fractions,setFractions]=useState<Fraction[]>([]), [feedback,setFeedback]=useState("Tutorial ready. Begin by inspecting the sample."), [choice,setChoice]=useState(""), [interpretations,setInterpretations]=useState<string[]>([]), [studentName,setStudentName]=useState(""), [recordId,setRecordId]=useState("");
 const heading=useRef<HTMLHeadingElement>(null), step=tutorialOne.steps[state.step], closest=closestContaminant(proteins), totalAct=activity(initial), specific=totalAct/totalProtein(initial);
 useEffect(()=>{heading.current?.focus()},[state.step]);
 const advance=()=>{setChoice("");setState(s=>({...s,step:Math.min(5,s.step+1)}));setFeedback(`Step ${Math.min(6,state.step+2)} ready.`)};
 const answer=(key:string,value:string,correct:boolean)=>{setChoice(value);setState(s=>({...s,answers:{...s.answers,[key]:value},checks:[...s.checks,`${key}:${correct?"correct":"retry"}`]}));setFeedback(correct?"Correct. Your reasoning is supported by the current evidence.":"Not yet. Use the hint and try again.")};
 const runSEC=()=>{const fs=fractionate(sample,"sec",{load:8,fraction:3});setFractions(fs);setFeedback("SEC complete. The protein trace is now available; activity is still hidden.");advance()};
 const toggleFraction=(id:string)=>setState(s=>({...s,selection:s.selection.includes(id)?s.selection.filter(x=>x!==id):[...s.selection,id]}));
 const evaluation=selectionEvaluation(fractions,state.selection), selected=fractions.filter(f=>state.selection.includes(f.id));
 const preview=selected.length?pool(sample,selected):null;
 const createPool=()=>{if(!evaluation.ok||!preview)return;setSample(preview);setFeedback("Pool created with the same mass-balance model used by the free explorer.");advance()};
 const evidence=sample.id!=="crude"?supportedInterpretations(initial,sample):null,tutorialMentorEvaluation=useMemo(()=>evaluateOperation({experimentId:sample.id,before:initial,after:sample,operation:"Guided SEC pool",property:"Molecular size",proteins}),[initial,sample]);
 function download(){if(!studentName.trim()){setFeedback("Enter your full name before generating the PDF record.");return}const attemptKeys=[...new Set([...Object.keys(state.answers),...state.checks.map(x=>x.split(":")[0])])],attempts=Object.fromEntries(attemptKeys.map(k=>[k,state.checks.filter(x=>x.startsWith(`${k}:`)).length]));const record=downloadCompletionPdf({studentName,tutorialNumber:"Guided Tutorial 1",tutorialTitle:"Find Enzyme A",version:"1.1",responses:{...state.answers,"selected fractions":state.selection.map(id=>`F${fractions.find(f=>f.id===id)?.n}`).join("–"),interpretation:interpretations.join(", "),reflection:state.reflection},attempts,outcome:{sample:sample.name,"total protein":`${totalProtein(sample).toFixed(1)} mg`,"total activity":`${activity(sample).toFixed(0)} U`,"specific activity":`${(activity(sample)/totalProtein(sample)).toFixed(2)} U/mg`,purity:`${purity(sample).toFixed(1)}%`,yield:`${(100*sample.activeTarget/initial.activeTarget).toFixed(1)}%`,"shared mentor classification":tutorialMentorEvaluation.classification}});setRecordId(record.completionId);setFeedback("PDF tutorial record downloaded. Submit your own record to Canvas.")}
 return <main className="tutorial-shell">
  <header className="tutorial-top"><button className="brand-button" onClick={onHome}><span className="mark">P</span><span><b>Protein Purification</b><small>Strategy Explorer</small></span></button><div><b>Guided Tutorial 1</b><small>{tutorialOne.title} · {tutorialOne.duration}</small></div><button onClick={onExit}>Exit to free explorer</button></header>
  <nav className="tutorial-progress" aria-label="Tutorial progress">{tutorialOne.steps.map((s,i)=><button key={s.id} className={i===state.step?"active":i<state.step?"done":""} disabled={i>state.step} onClick={()=>i<=state.step&&setState(x=>({...x,step:i}))}><span>{i<state.step?"✓":i+1}</span><small>{s.title}</small></button>)}</nav>
  <section className="tutorial-layout"><aside className="tutorial-guide"><span className="eyebrow">STEP {state.step+1} OF 6</span><h1 ref={heading} tabIndex={-1}>{step.title}</h1><p>{step.goal}</p><div className="guide-prompt"><b>Your task</b><p>{step.prompt}</p></div><p className="exit-note">You can exit at any time. Reopen Tutorial from the explorer header to start again.</p></aside>
   <section className="tutorial-stage">
    {state.step===0&&<><Title eyebrow="STARTING MATERIAL" title="Crude bacterial lysate" text="A mixture of eight proteins. Enzyme A is active, but it is not yet pure."/><MetricCards sample={initial}/><div className="knowledge"><h2>Knowledge check</h2><p>Which metric best combines activity with the amount of protein?</p>{[["Total activity","activity"],["Specific activity","specific"],["Volume","volume"]].map(([label,val])=><button key={val} onClick={()=>answer("starting-metric",val,val==="specific")}>{label}</button>)}<div className={answerClass(!!state.answers["starting-metric"],choice==="specific")} role="status">{state.answers["starting-metric"]&&(choice==="specific"?`Yes. Specific activity = ${round(specific,2)} U/mg for this sample.`:"Hint: look for a ratio with activity in the numerator and protein in the denominator.")}</div></div><Next enabled={choice==="specific"} onClick={advance}/></>}
    {state.step===1&&<><Title eyebrow="SIZE EVIDENCE" title="Compare molecular masses" text="SEC separates proteins by hydrodynamic size; larger proteins generally elute earlier."/><div className="mass-map">{proteins.slice().sort((a,b)=>b.mass-a.mass).map(p=><div className={p.id==="enzyme-a"?"target":""} key={p.id}><span>{p.name}</span><i style={{width:`${p.mass}%`}}/><b>{p.mass} kDa</b></div>)}</div><div className="science-note"><b>Closest contaminant</b><p>{closest.name} is {closest.mass} kDa—only {closest.difference} kDa from Enzyme A (62 kDa). Complete separation by SEC is unlikely.</p></div><div className="knowledge"><p>Which property is used here?</p>{["Molecular size","Net charge","Catalytic activity"].map(x=><button key={x} onClick={()=>answer("sec-property",x,x==="Molecular size")}>{x}</button>)}<div className={answerClass(!!state.answers["sec-property"],choice==="Molecular size")} role="status">{state.answers["sec-property"]&&(choice==="Molecular size"?"Correct. SEC resolves by size, not by charge or enzyme function.":"Try again: focus on the values shown in kDa.")}</div></div><Next enabled={choice==="Molecular size"} onClick={advance}/></>}
    {state.step===2&&<><Title eyebrow="SEC SETUP" title="Predict before you run" text="Recommended setup: SEC-75 column, 8 mL load, 3 mL fractions."/><div className="config-summary"><span><small>COLUMN</small><b>SEC-75 · 3–80 kDa</b></span><span><small>LOAD</small><b>8 mL</b></span><span><small>FRACTION SIZE</small><b>3 mL</b></span></div><div className="knowledge"><p>Which prediction is most defensible?</p><button onClick={()=>answer("sec-prediction","larger-first-overlap",true)}>Larger proteins elute earlier, but 60–66 kDa proteins may overlap Enzyme A.</button><button onClick={()=>answer("sec-prediction","target-alone",false)}>Enzyme A will form a perfectly isolated peak.</button><button onClick={()=>answer("sec-prediction","small-first",false)}>The smallest proteins will elute first.</button><div className={answerClass(!!state.answers["sec-prediction"],choice==="larger-first-overlap")} role="status">{state.answers["sec-prediction"]&&(choice==="larger-first-overlap"?"Prediction committed. The model will now generate fractions from the current sample.":"Use SEC elution order and the 2 kDa nearest-neighbor gap.")}</div></div><button className="tutorial-cta" disabled={choice!=="larger-first-overlap"} onClick={runSEC}>Run size-exclusion chromatography →</button></>}
    {state.step===3&&<><Title eyebrow="MODELED CHROMATOGRAM" title="Protein signal is not identity" text="A₂₈₀ shows where protein eluted, but every protein contributes to that signal."/><div className="chart-legend"><b>What do the colors mean?</b><span><i className="protein-key"/>Blue-gray: Total protein, measured by A₂₈₀</span><span><i className="activity-key">✦</i>Orange: Enzyme A activity, measured by the activity assay</span></div><p className="chart-explainer">Many proteins contribute to the A₂₈₀ signal, but only fractions containing active Enzyme A produce activity in the assay.</p><TutorialChart fs={fractions} activityVisible={state.assayRevealed} selected={state.selection}/>{!state.assayRevealed?<div className="knowledge"><p>Can this protein trace alone identify Enzyme A?</p><button onClick={()=>answer("protein-alone","yes",false)}>Yes</button><button onClick={()=>{answer("protein-alone","no",true);setState(s=>({...s,assayRevealed:true}))}}>No—run the enzyme assay</button><div className={answerClass(!!state.answers["protein-alone"],choice==="no")} role="status">{state.answers["protein-alone"]&&(choice==="no"?"Exactly. The activity overlay now provides target-specific evidence.":"A₂₈₀ is shared by all proteins, so it cannot establish identity.")}</div></div>:<><div className="science-note success"><b>Activity assay revealed</b><p>Select a contiguous set of fractions around the activity peak. Click fractions below, then check the pool.</p></div><div className="fraction-picker">{fractions.map(f=><button aria-pressed={state.selection.includes(f.id)} className={state.selection.includes(f.id)?"selected":""} key={f.id} onClick={()=>toggleFraction(f.id)}><b>F{f.n}</b><small>{round(f.activity,0)} U</small></button>)}</div><button className="tutorial-cta secondary" onClick={()=>{setFeedback(evaluation.message);setState(s=>({...s,checks:[...s.checks,`fraction-selection:${evaluation.kind}`]}))}}>Check selected pool</button><div className={answerClass(!!state.selection.length,evaluation.ok)} role="status">{state.selection.length?evaluation.message:"Select fractions to evaluate recovery and contamination."}</div><Next enabled={evaluation.ok} onClick={advance}/></>}</>}
    {state.step===4&&preview&&<><Title eyebrow="POOL PREVIEW" title={`Pool F${selected[0].n}–F${selected[selected.length-1].n}`} text="Preview the mass balance before committing the new material state."/><div className="compare-metrics"><MetricCards sample={initial}/><span className="compare-arrow">→</span><MetricCards sample={preview}/></div><div className="knowledge"><p>What is the main tradeoff of making this pool narrower?</p><button onClick={()=>answer("pool-tradeoff","purity-recovery",true)}>Purity may improve while target recovery falls.</button><button onClick={()=>answer("pool-tradeoff","both-always-rise",false)}>Purity and recovery must always rise together.</button><div className={answerClass(!!state.answers["pool-tradeoff"],choice==="purity-recovery")} role="status">{state.answers["pool-tradeoff"]&&(choice==="purity-recovery"?"Correct. Pool boundaries trade recovery for selectivity.":"A narrower window leaves some active target behind along with contaminants.")}</div></div><button className="tutorial-cta" disabled={choice!=="purity-recovery"} onClick={createPool}>Create this pool →</button></>}
    {state.step===5&&evidence&&<><Title eyebrow="FINAL EVIDENCE" title="More purified, not perfectly pure" text="Compare the crude lysate with the pool and use every metric—not band appearance alone."/><div className="gel-comparison"><MiniGel sample={initial} label="Crude lysate"/><MiniGel sample={sample} label={sample.name}/></div><PurificationTable initial={initial} pooled={sample}/><div className="knowledge"><p>Select the two supported conclusions.</p>{[["Purity improved","purity"],["Some active Enzyme A was retained","activity"],["The pool is perfectly pure","perfect"]].map(([label,id])=><label key={id}><input type="checkbox" checked={interpretations.includes(id)} onChange={()=>setInterpretations(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}/>{label}</label>)}<textarea aria-label="Reflection" placeholder="In one or two sentences, explain why the final pool is improved but not perfectly pure." value={state.reflection} onChange={e=>setState(s=>({...s,reflection:e.target.value}))}/><div className={answerClass(interpretations.length>0,interpretations.includes("purity")&&interpretations.includes("activity")&&!interpretations.includes("perfect"))} role="status">{interpretations.length>0&&(interpretations.includes("purity")&&interpretations.includes("activity")&&!interpretations.includes("perfect")?"Supported: specific activity and purity increased, activity remains, and nearby-mass contaminants still co-elute.":"Recheck the gel, activity, and purity values. Improved does not mean perfectly pure.")}</div></div>{!state.completed?<button className="tutorial-cta" disabled={!(interpretations.includes("purity")&&interpretations.includes("activity")&&!interpretations.includes("perfect")&&state.reflection.trim().length>12)} onClick={()=>{setState(s=>({...s,completed:true}));setFeedback("Tutorial complete. Enter your name to create a Canvas-ready PDF record.")}}>Complete tutorial →</button>:<div className="completion"><span>✓</span><h2>Tutorial 1 complete</h2><p>You used molecular size, enzyme activity, pooling tradeoffs, and purification metrics to find Enzyme A.</p><label className="student-name">Full name<input value={studentName} onChange={e=>setStudentName(e.target.value)} autoComplete="off" placeholder="Enter your full name"/></label><button disabled={!studentName.trim()} onClick={download}>Download PDF Tutorial Record</button><p className="privacy-note">Your record includes your name, completion time, responses, and a unique completion ID. Submit your own record to Canvas. Your name stays in this session and is not transmitted or permanently stored.</p>{recordId&&<small>Completion ID: {recordId}</small>}</div>}</>}
   </section></section><div className="tutorial-status" aria-live="polite">{feedback}</div>
 </main>
}

function Title({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="tutorial-title"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}
function Next({enabled,onClick}:{enabled:boolean;onClick:()=>void}){return <button className="tutorial-cta" disabled={!enabled} onClick={onClick}>Continue →</button>}
function MetricCards({sample}:{sample:Sample}){return <div className="tutorial-metrics">{[["Total protein",`${round(totalProtein(sample))} mg`],["Total activity",`${round(activity(sample),0)} U`],["Specific activity",`${round(activity(sample)/totalProtein(sample),2)} U/mg`],["Estimated purity",`${round(purity(sample))}%`]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div>}
function TutorialChart({fs,activityVisible,selected}:{fs:Fraction[];activityVisible:boolean;selected:string[]}){const proteinMax=Math.max(...fs.map(f=>f.absorbance),1),actMax=Math.max(...fs.map(f=>f.activity),1);return <div className="chart-frame"><span className="axis left-axis">A₂₈₀ / total protein signal</span><div className="tutorial-chart" aria-label={activityVisible?"Chromatogram with total protein and Enzyme A activity on separate scales":"Chromatogram with total protein signal only"}>{fs.map(f=><div className={selected.includes(f.id)?"selected":""} key={f.id}><i className="protein" style={{height:`${f.absorbance/proteinMax*90}%`}}/>{activityVisible&&<i className="activity" aria-label={`Fraction ${f.n}, Enzyme A activity ${round(f.activity,0)} units`} style={{height:`${f.activity/actMax*80}%`}}/>}<small>F{f.n}</small></div>)}</div><span className="axis right-axis">Enzyme A activity (U)</span><b className="x-axis">Fraction →</b></div>}
function MiniGel({sample,label}:{sample:Sample;label:string}){const max=Math.max(...Object.values(sample.masses));return <figure className="gel-sample"><div className="lane" aria-label={`Modeled SDS-PAGE gel for ${label}`}>{proteins.map(p=><i key={p.id} style={{top:`${(100-p.mass)/1.05}%`,opacity:.1+.85*(sample.masses[p.id]||0)/max}}/>)}</div><figcaption>{label}</figcaption></figure>}
function PurificationTable({initial,pooled}:{initial:Sample;pooled:Sample}){const row=(s:Sample)=>({protein:totalProtein(s),act:activity(s),spec:activity(s)/totalProtein(s),purity:purity(s),yield:100*s.activeTarget/initial.activeTarget});return <div className="table-scroll"><table><thead><tr><th>Sample</th><th>Total protein</th><th>Total activity</th><th>Specific activity</th><th>Purity</th><th>Yield</th></tr></thead><tbody>{[[initial.name,row(initial)],[pooled.name,row(pooled)]].map(([name,r]:any)=><tr key={name}><td>{name}</td><td>{round(r.protein)} mg</td><td>{round(r.act,0)} U</td><td>{round(r.spec,2)} U/mg</td><td>{round(r.purity)}%</td><td>{round(r.yield)}%</td></tr>)}</tbody></table></div>}
